# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: romankrds
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: fbh
# "service" is the name of this project. This will also be added to your AWS resource names.
service: FBHelper

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.11

package:
  exclude:
    - node_modules/**
    - .git/**
    - .idea/**
    - .vscode/**
    - .idea/**
    - .venv/**
    - tests/**
    - docs/**

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements
